### ISSUE TITLE
Hello j ai detecte un petit bug si tu veux essayer de fix

### ISSUE THREAD

**Issue by ripitchip** [MorganKryze/Portfolio#3]
![image](https://github.com/user-attachments/assets/70910c14-a615-46dc-9234-9dfba2929149)
En gros qand tu scroll la nav bar et le text overlap voila <3

**Comment by ripitchip** [comment]
En faite c est plus t as pas de transparence donc on peut pas lire le texte quand t as des images qui passe en dessous ect

**Comment by MorganKryze** [comment]
Merci du feedback, voici le fix que je propose : [`c5a1c90`](https://github.com/MorganKryze/Portfolio/tree/c5a1c90d7990e0dbda2359648ed0b74f5ed7c7e8)

**Comment by ripitchip** [comment]
Yes ca marche apres tu peux essayer de ou faire disparaitre la top bar ou mettre du blur ca marche aussi
